api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        html:     ['text/html']
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: []
        # public: true
    # defaults:
        # cache_headers:
            # max_age: 0
            # shared_max_age: 3600
            # vary: ['Content-Type', 'Authorization', 'Origin']